/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pages;

import Ferme.Dao.Codificador;
import Ferme.Dao.EmpleadoDao;
import Ferme.Dao.Smtp;
import Ferme.Dto.Empleado;
import javax.swing.JOptionPane;

/**
 *
 * @author wwwvi
 */
public class RecuperarPass extends javax.swing.JFrame {

    public RecuperarPass() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        LblLogIn = new javax.swing.JLabel();
        LblLogIn2 = new javax.swing.JLabel();
        LblLogIn3 = new javax.swing.JLabel();
        Run = new rojeru_san.RSMTextFull();
        lblRun = new javax.swing.JLabel();
        email1 = new rojeru_san.RSMTextFull();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setBackground(new java.awt.Color(102, 102, 255));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Enviar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        LblLogIn.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        LblLogIn.setForeground(new java.awt.Color(0, 0, 0));
        LblLogIn.setText("Recuperar clave de Usuario");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LblLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LblLogIn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        LblLogIn2.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        LblLogIn2.setForeground(new java.awt.Color(0, 0, 0));
        LblLogIn2.setText("Email:");

        LblLogIn3.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        LblLogIn3.setForeground(new java.awt.Color(0, 0, 0));

        Run.setPlaceholder("Ingrese su Run ");
        Run.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RunActionPerformed(evt);
            }
        });

        lblRun.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        lblRun.setForeground(new java.awt.Color(0, 0, 0));
        lblRun.setText("Run:");

        email1.setPlaceholder("Email");
        email1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(543, 543, 543)
                        .addComponent(LblLogIn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblLogIn2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblRun, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(Run, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(257, 257, 257)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(217, Short.MAX_VALUE)
                    .addComponent(email1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(169, 169, 169)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(93, 93, 93))
                            .addComponent(LblLogIn2))
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 152, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRun)
                            .addComponent(Run, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(LblLogIn3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(27, 27, 27))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(102, 102, 102)
                    .addComponent(email1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(127, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        EmpleadoDao empdao = new EmpleadoDao();
        Smtp smtp = new Smtp();
        Empleado empdto;

        String user = email1.getText();
        String run = Run.getText();

        empdto = empdao.BuscarEmpleado(run);
        if (empdto.correo.equals(user)) {
            String pass = empdto.contrasena;
            String destina = empdto.correo;
            String asunto = "Recuperacion de Password";
            String cuerpo = " \n"
                    + "<!DOCTYPE html>    \n"
                    + "<html>    \n"
                    + "<head>\n"
                    + "  \n"
                    + "</head>    \n"
                    + "<body marginheight=0 marginwidth=0 topmargin=0 leftmargin=0 style=\"height: 100% !important; margin: 0; padding: 0; width: 100% !important;min-width: 100%;\">    \n"
                    + "    \n"
                    + "<table name=\"bmeMainContent\" style=\"border-radius: 0px; border-collapse: separate; border-spacing: 0px; border: 0px none transparent; overflow: visible;\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" align=\"center\"> <tbody><tr><td width=\"100%\" class=\"blk_container bmeHolder\" name=\"bmeHeader\" valign=\"top\" align=\"center\" style=\"border: 0px none transparent; background-color: rgb(255, 255, 255);\" bgcolor=\"#ffffff\"><div id=\"dv_9\" class=\"blk_wrapper\">    \n"
                    + "<table width=\"600\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" class=\"blk\" name=\"blk_divider\" style=\"\"><tbody><tr><td class=\"tblCellMain\" style=\"padding: 10px 20px;\">    \n"
                    + "\n"
                    + "<table class=\"tblLine\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" width=\"100%\" style=\"border-top-width: 0px; border-top-style: none; min-width: 1px;\"><tbody><tr><td><span></span></td></tr></tbody>    \n"
                    + "</table></td></tr></tbody>   \n"
                    + "</table></div><div id=\"dv_1\" class=\"blk_wrapper\">    \n"
                    + "<table width=\"600\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" class=\"blk\" name=\"blk_image\"><tbody><tr><td>    \n"
                    + "<table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\"><tbody><tr><td align=\"center\" class=\"bmeImage\" style=\"border-collapse: collapse; padding: 10px 0px;\"><img    \n"
                    + " src=\"https://i.postimg.cc/1XzkVFSp/FERME-Logo.png\" class=\"mobile-img-large\" width=\"600\" style=\"max-width: 1200px; display: block; width: 600px;\" alt=\"\" border=\"0\"></td></tr></tbody>    \n"
                    + "</table></td></tr></tbody>    \n"
                    + "</table></div><div id=\"dv_11\" class=\"blk_wrapper\">    \n"
                    + "<table width=\"600\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" class=\"blk\" name=\"blk_divider\" style=\"\"><tbody><tr><td class=\"tblCellMain\" style=\"padding: 20px;\">    \n"
                    + "<table class=\"tblLine\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" width=\"100%\" style=\"border-top-width: 0px; border-top-style: none; min-width: 1px;\"><tbody><tr><td><span></span></td></tr></tbody>    \n"
                    + "</table></td></tr></tbody>    \n"
                    + "</table></div>\n"
                    + "</td></tr> <tr><td width=\"100%\" class=\"blk_container bmeHolder bmeBody\" name=\"bmeBody\" valign=\"top\" align=\"center\" style=\"color: rgb(56, 56, 56); border: 0px none transparent; background-color: rgb(255, 255, 255);\" bgcolor=\"#ffffff\"><div id=\"dv_13\" class=\"blk_wrapper\">    \n"
                    + "<table width=\"600\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" class=\"blk\" name=\"blk_divider\" style=\"\"><tbody><tr><td class=\"tblCellMain\" style=\"padding: 15px 20px;\">    \n"
                    + "<table class=\"tblLine\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" width=\"100%\" style=\"border-top-width: 0px; border-top-style: none; min-width: 1px;\"><tbody><tr><td><span></span></td></tr></tbody>    \n"
                    + "</table></td></tr></tbody>    \n"
                    + "</table></div><div id=\"dv_12\" class=\"blk_wrapper\">    \n"
                    + "<table width=\"600\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" class=\"blk\" name=\"blk_button\" style=\"\"><tbody><tr><td width=\"20\"></td><td align=\"center\">    \n"
                    + "<table class=\"tblContainer\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" width=\"100%\"><tbody><tr><td height=\"20\"></td></tr><tr><td align=\"center\">    \n"
                    + "<table cellspacing=\"0\" cellpadding=\"0\" border=\"0\" class=\"bmeButton\" align=\"center\" style=\"border-collapse: separate;\"><tbody><tr><td style=\"border-radius: 0px; border: 1px solid rgb(69, 153, 232); text-align: center; font-family: Arial, Helvetica, sans-serif; font-size: 14px; padding: 15px 40px; font-weight: normal; border-collapse: separate;\" class=\"bmeButtonText\"><span style=\"font-family: 'Arial Narrow', 'Arial MT Condensed Light', sans-serif; font-size: 24px; color: rgb(255, 251, 255);\">    \n"
                    + "<a style=\"color: rgb(0, 0, 0); text-decoration: none;\" target=\"_blank\">Recuperacion de Contraseña </a></span></td></tr></tbody>    \n"
                    + "</table></td></tr><tr><td height=\"20\"></td></tr></tbody>    \n"
                    + "</table></td><td width=\"20\"></td></tr></tbody>    \n"
                    + "</table></div><div id=\"dv_14\" class=\"blk_wrapper\">    \n"
                    + "<table width=\"600\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" class=\"blk\" name=\"blk_text\"><tbody><tr><td>    \n"
                    + "<table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" width=\"100%\" class=\"bmeContainerRow\"><tbody><tr><td class=\"tdPart\" valign=\"top\" align=\"center\">    \n"
                    + "<table cellspacing=\"0\" cellpadding=\"0\" border=\"0\" width=\"600\" name=\"tblText\" style=\"float:left; background-color:transparent;\" align=\"left\" class=\"tblText\"><tbody><tr><td valign=\"top\" align=\"left\" name=\"tblCell\" style=\"padding: 10px 20px; font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-weight: 400; color: rgb(56, 56, 56); text-align: left;\" class=\"tblCell\"><div style=\"line-height: 200%; text-align: center;\"><span style=\"font-size: 14px; font-family: Arial, Helvetica, sans-serif; color: #000000; line-height: 200%;\">Hola Esperando que tengas un buen dia laboral a continuacion te hacemos envio de tu contraseña para acceder a nustro sistema Saludos</span></div></td></tr></tbody>    \n"
                    + "\n" + empdto.contrasena
                    + "</table></td></tr><tr><td height=\"20\"></td></tr></tbody>    \n"
                    + "</table></td><td width=\"20\"></td></tr></tbody>    \n"
                    + "</table></div>\n"
                    + "</td></tr> <tr><td width=\"100%\" class=\"blk_container bmeHolder\" name=\"bmePreFooter\" valign=\"top\" align=\"center\" style=\"border: 0px none transparent; background-color: rgb(255, 255, 255);\" bgcolor=\"#ffffff\">\n"
                    + "<div id=\"dv_4\" class=\"blk_wrapper\">    \n"
                    + "<table width=\"600\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" class=\"blk\" name=\"blk_divider\" style=\"\"><tbody><tr><td class=\"tblCellMain\" style=\"padding: 30px 20px;\">    \n"
                    + "<table class=\"tblLine\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" width=\"100%\" style=\"border-top-width: 0px; border-top-style: none; min-width: 1px;\"><tbody><tr><td><span></span></td></tr></tbody>    \n"
                    + "\n"
                    + "</table></div><div id=\"dv_7\" class=\"blk_wrapper\">    \n"
                    + "<table width=\"600\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" class=\"blk\" name=\"blk_footer\" style=\"\"><tbody><tr><td name=\"tblCell\" class=\"tblCell\" style=\"padding:20px;\" valign=\"top\" align=\"left\">    \n"
                    + "<table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" width=\"100%\"><tbody><tr><td name=\"bmeBadgeText\" style=\"text-align:left; word-break: break-word;\" align=\"left\"><span id=\"spnFooterText\" style=\"font-family: Arial, Helvetica, sans-serif; font-weight: normal; font-size: 11px; line-height: 140%;\">Este mensaje de correo electrónico fue enviado a " + empdto.correo + " , por equipoferme2020@gmail.com |\n"
                    + "	<br>Ferreteria Ferme | Calle Falsa 123 | Santiago | Santiago | Chile </span>    \n"
                    + "<br>    ";
            System.out.println(pass);
            smtp.enviarSmtp(destina, asunto, cuerpo);
        } else {
            JOptionPane.showMessageDialog(null, "Este email no pertenece al usuario que busca");
        }

        this.setVisible(false);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void RunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RunActionPerformed

    private void email1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email1ActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecuperarPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecuperarPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecuperarPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecuperarPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecuperarPass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblLogIn;
    private javax.swing.JLabel LblLogIn2;
    private javax.swing.JLabel LblLogIn3;
    private rojeru_san.RSMTextFull Run;
    private rojeru_san.RSMTextFull email1;
    private javax.swing.JButton jButton1;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblRun;
    // End of variables declaration//GEN-END:variables
}
